server:
  port: 8081    #port number

spring:
  application:
    name: gateway-service    #service name
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.eureka.app: DEBUG
