AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 bucket

Resources:
  PriyaS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: priya-day09-bucket-cf

Outputs:
  BucketName:
    Value: !Ref PriyaS3Bucket