version: '3.8'
services:
  hospital:
    image: student-management-app:latest
    container_name: student-app
    ports:
      - "8080:8080"
    networks:
      - student-network

networks:
  student-network:
    driver: bridge