AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Create ECS Cluster
Parameters:
  Environment:
    Type: String
    Default: Test
  ShortSolution:
    Type: String
    Default: priya

Resources:
  EcsCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      CapacityProviders:
        - 'FARGATE'
      ClusterName: !Sub '${ShortSolution}-${Environment}-microservice-cluster'
      ClusterSettings:
        - Name: containerInsights
          Value: enabled

Outputs:
  EcsClusterTrainingPriya:
    Value: !Ref EcsCluster
    Export:
      Name: 'EcsClusterTrainingPriya'

