apiVersion: v1
kind: Namespace
metadata:
  name: day17-priya
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: priya-ecr-app
  namespace: day17-priya
spec:
  replicas: 2
  selector:
    matchLabels:
      app: priya-ecr-app
  template:
    metadata:
      labels:
        app: priya-ecr-app
    spec:
      containers:
        - name: priya-ecr-container
          image: 386757865964.dkr.ecr.us-east-1.amazonaws.com/priya-ecr:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
