server:
  port: 8083    #default port where the service will be started

spring:
  application:
    name: student-service   #current service name to be used by the eureka server

eureka:         #tells about the Eureka server details and its refresh time
  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
#    lease:
#      duration: 5
 
logging:
  level:
    com.eureka.app: DEBUG
